export enum NlpTool {
    Ner = "ner",
    MorphAnalyzer = "morphanalyzer",
    IsTurkish = "isturkish",
    MorphGenerator = "morphgenerator",
    SentenceSplitter = "sentencesplitter",
    Tokenizer = "tokenizer",
    Normalize = "normalize",
    Deasciifier = "deasciifier",
    Vowelizer = "Vowelizer",
    DepParserFormal = "DepParserFormal",
    DepParserNoisy = "DepParserNoisy",
    SpellCheck = "spellcheck",
    Disambiguator = "disambiguator",
    PipelineFormal = "pipelineFormal",
    PipelineNoisy = "pipelineNoisy",
    PipelineFormalWithSplitter = "pipelineFormalwSentenceSplitter",
    PipelineNoisyWithSplitter = "pipelineNoisywSentenceSplitter",
    PipelineSSMorph = "pipelineSSMorph",
}